// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mtype.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mtype.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::EnumDescriptor* MessageTypes_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_mtype_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_mtype_2eproto() {
  protobuf_AddDesc_mtype_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mtype.proto");
  GOOGLE_CHECK(file != NULL);
  MessageTypes_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mtype_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_mtype_2eproto() {
}

void protobuf_AddDesc_mtype_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_mtype_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013mtype.proto*\231\001\n\014MessageTypes\022\024\n\020MTYPE_"
    "KERNEL_RUN\020\001\022\025\n\021MTYPE_KERNEL_DONE\020\002\022\017\n\013M"
    "TYPE_REPLY\020\003\022\025\n\021MTYPE_MOTIF_COUNT\020\004\022\031\n\025M"
    "TYPE_MOTIF_COUNT_POS\020\005\022\031\n\025MTYPE_MOTIF_CO"
    "UNT_NEG\020\006", 169);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mtype.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mtype_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mtype_2eproto {
  StaticDescriptorInitializer_mtype_2eproto() {
    protobuf_AddDesc_mtype_2eproto();
  }
} static_descriptor_initializer_mtype_2eproto_;
const ::google::protobuf::EnumDescriptor* MessageTypes_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageTypes_descriptor_;
}
bool MessageTypes_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
